server:
  port: 9000
  servlet:
    context-path: /auth-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ledzer_microservice_authdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
    show-sql: true
    generate-ddl: true
  application:
    name: auth-service
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: -*
        exclude: env,beans
      
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/auth-api/oauth/check_token
      user-info-uri: http://localhost:9191/auth-api/user/me
    client:
      client-id: mobile
      client-secret: pin
      access-token-uri: http://localhost:9191/auth-api/oauth/token
      user-authorization-uri: http://localhost:9191/auth-api/oauth/authorize
      authorized-grant-types : authorization_code,refresh_token,password
      access-token-validity-seconds: 20000
      refresh-token-validity-seconds: 20000
    